### ISSUE TITLE
[Bug] Wireless Charging not accepting energy

### ISSUE THREAD

**Issue by LobaCW** [SuperMartijn642/WirelessChargers#1]
**Version Info**
- Minecraft, 1.12.2
- Wireless Chargers, 1.0.3

**Description of the Bug**
Any of the chargers are accepting energy, I tested with cable from all sides, with mekanism and xnet mods only

**Steps to Reproduce**
Try to put energy in any charger from cables or cube energy (both from mekanism)
Also, in case it is a bug with other mod that I don't know of, here is the modlist: https://pastebin.com/TzSyApDe

**Screenshots**
![2021-11-18_18 56 45](https://user-images.githubusercontent.com/81968724/142496748-0f119fb4-5485-4217-8c35-294307b075fd.png)
![2021-11-18_18 56 48](https://user-images.githubusercontent.com/81968724/142496767-0b11ee70-95bf-4cb3-9899-d6b83ee06d1a.png)

**Comment by SuperMartijn642** [comment]
I fixed it now in Wireless Chargers version 1.0.3a for 1.12.

Thank you for reporting the issue!
