### ISSUE TITLE
[Bug] Minecraft freezes during loading if the config file is present

### ISSUE THREAD

**Issue by Peca21** [SuperMartijn642/WirelessChargers#10]
**Version Info**
- Minecraft 1.18.2
- wirelesschargers-1.0.6-forge-mc1.18
supermartijn642configlib-1.1.0-forge-mc1.18
supermartijn642corelib-1.0.18-forge-mc1.18

**Description of the Bug**
When I start my modpack it freezes at the white screen during loading, 
If I delete the config file for WirelessChargers minecraft starts, but I have to delete the config every time I want to start the game
This started after I updated supermartijn642configlib but redownloading the old version somehow still doesn't fix it.
EDIT: Downgrading config lib AND deleting a config file fixes it.
EDIT: forgot the log https://paste.ee/p/W5d5k

**Steps to Reproduce**
1. Start minecraft
2. Wait

**Comment by SuperMartijn642** [comment]
I fixed it now in my config library version 1.1.1.
Thank you for reporting the issue!
