### ISSUE TITLE
[Bug] [1.18.2] config file overwrited every server start and roll back any changes

### ISSUE THREAD

**Issue by ptk2003** [SuperMartijn642/WirelessChargers#11]
**Version Info**
- Minecraft, 1.18.2-forge-40.1.21, SMP
- Wireless Chargers,
- supermartijn642corelib-1.0.18-forge-mc1.18
- supermartijn642configlib-1.1.3-forge-mc1.18
- SuperMartijn642_wirelesschargers-1.0.6-forge-mc1.18

**Description of the Bug**
the config file config\wirelesschargers-common.toml overwrited every server start and roll back any changes - cannot increase any value.
I write in file after server stop.

in past 1.16.5-forge-36.2.23 it worked fine.

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by ptk2003** [comment]
in WirelessChargers-1.18\gradle\wrapper\gradle-wrapper.properties incorrect "distributionUrl"
Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-7.2-20210702220150+0000-bin.zip

compiled with distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip

**Comment by SuperMartijn642** [comment]
No clue what you're saying in your last comment.

**Comment by SuperMartijn642** [comment]
It is fixed now in version 1.1.4 of my config lib.
Thank you for reporting the issue!
