### ISSUE TITLE
[Question] Is there a reason I can only pump in 2kfe/t per side?

### ISSUE THREAD

**Issue by MrPurple6411** [SuperMartijn642/WirelessChargers#18]
**Question**

I am trying to setup a Phyto grow MA farm on ATM8 1.0.18 and I have noticed that these advanced block chargers just cannot keep up.

While they WILL put 200fe/t into every machine in range they will only ever allow 2k to be put into them per side for a max of 10kfe/t while this sounds like it should be plenty of power it does not seem to be as inside that 7x7 area I have 112 phyto insolators  each using 320fe/t for a total of 35,840fe/t  and while I have 4 advanced wireless chargers in the middle to make sure they all have sufficient power I am still somehow getting 2 of the 4 sitting at 10kfe at all times because they wont let more then 10kfe/t into them.

![image](https://github.com/SuperMartijn642/WirelessChargers/assets/7858500/dd47140d-0406-400d-ae0c-3f487da79a97)

this middle one gets to do 8kfe/t because its pushing into all 4.
![image](https://github.com/SuperMartijn642/WirelessChargers/assets/7858500/f1398da3-af65-457c-918f-26c22c917879)

**Comment by SuperMartijn642** [comment]
Seems I set an insertion limit of 10 * the max charging rate in the code. However, as you have pointed out, I do agree that it is quite easy to get to charging more than 10 blocks.
I will probably add a config option for it and also increase the default to be a bit more realistic.

**Comment by SuperMartijn642** [comment]
I have increased the insertion limit to 100 times the charger's transfer rate now, so hopefully that's a bit better 🙂
Thank you for letting me know!
