### ISSUE TITLE
[Bug] Image of Wireless charger appearing in places it should not be and on other mods creative screens

### ISSUE THREAD

**Issue by Gamerbolts** [SuperMartijn642/WirelessChargers#19]
**Version Info**
- Minecraft, ... Fabric 1.19.2
- Wireless Chargers, ... 1.0.8a

**Description of the Bug**
On nearly every creative tab and on the inventory screen I am seeing the image of the wireless chargers, not sure if it is your mod or another that is doing something strange.

**Steps to Reproduce**
I am creating a rather large modpack. I have not tested the mod by itself

**Screenshots**
![image](https://github.com/SuperMartijn642/WirelessChargers/assets/20451601/7b79c83d-0717-42a9-afc6-ecdcfbf63b14)
![image](https://github.com/SuperMartijn642/WirelessChargers/assets/20451601/220a0007-e981-4f9c-bfdb-d0b3f7a188b3)

Any help is appreciated. Thank you!

**Comment by Gamerbolts** [comment]
I just realized the Trash Can and Tesseract mods are also in my modpack and doing the same thing. And also just realized all 3 are your creations lol. Any help please :)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.9d of my core library.
Thank you for reporting the issue!
