### ISSUE TITLE
[Crash] 1.19.2 Client Crash when trying to render any Wireless Charger

### ISSUE THREAD

**Issue by jellyfishhunter** [SuperMartijn642/WirelessChargers#21]
**Version Info**
- Minecraft, 1.19.2
- Wireless Chargers, 1.0.8 & 1.0.9

**Steps to Reproduce**
Client crashes as soon as a wireless charger is placed or the player enters a chunk with an existing wireless charger.
This might only occur in combination of another mod within my modpack. But maybe there's something you can do about it.

**Crash report (~/logs/latest.log)**
https://pastebin.com/6z35D4Zu

**Comment by SuperMartijn642** [comment]
Caused by Out of Sight. Please report the issue to them.
