### ISSUE TITLE
[Crash] ... Crashes server when connected to Industrial Revolution cables

### ISSUE THREAD

**Issue by Teboran** [SuperMartijn642/WirelessChargers#22]
**Version Info**
Minecraft: 1.19.2
Fabric API: 0.76.0+1.19.2
Industrial Revolution: 1.15.1-beta
Modpack: All of Fabric 1.9.1
Wireless Chargers: 1.0.9-fabric-mc1.19.2
**Steps to Reproduce**
...Attach a wireless charger to an Indrev cable

**Crash report (~/logs/latest.log)**
...
[crash-2023-08-15_15.15.37-server.txt](https://github.com/SuperMartijn642/WirelessChargers/files/12352459/crash-2023-08-15_15.15.37-server.txt)

**Comment by SuperMartijn642** [comment]
It seems to be working fine
![image](https://github.com/SuperMartijn642/WirelessChargers/assets/12382965/2dff2035-49a3-470a-8b38-fecb4ced7db2)
