### ISSUE TITLE
[Question] Possible to make GUI panel use image instead of being generated through code

### ISSUE THREAD

**Issue by Nycto97** [SuperMartijn642/WirelessChargers#23]
**Question**

Hi!

I use the [Default Dark Mode](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode) resource pack. Lately I've been adding my own support for some mods to make the GUIs in the same dark style of this resource pack, as shown here: https://github.com/nebuIr/Default-Dark-Mode/pull/155 (made many more, just only commiting easy ones where I'm most sure about that I did everything right)

I wanted to do this for the GUI of this mod as well, but I noticed there's no files for the actual GUI panel. There's only files for the buttons and the energy bar.

Would it be possible and are you willing to use an image file for the background of the GUI panel (as done in Moving Elevators) instead of it being generated through code, so that resource pack/modpack makers are able to change the style of the GUI panel?

**Comment by SuperMartijn642** [comment]
It is using an image, however it is located in my core library and shared between some of my mods. You can find it here: https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/blob/forge-1.16/src/main/resources/assets/supermartijn642corelib/textures/gui/background.png

**Comment by Nycto97** [comment]
Oh, I see :) Thank you!
