### ISSUE TITLE
[Feature] Wireless Chargers don't support Iron JetPacks

### ISSUE THREAD

**Issue by xDomso** [SuperMartijn642/WirelessChargers#24]
As in title.
Please add support for Iron JetPacks mod to charhe jetpack with is wearing

**Comment by SuperMartijn642** [comment]
If it's not charging jetpacks from Iron Jetpacks, that's a bug, so please use the bug template.

What version of Minecraft are you using? What version of Wireless Chargers are you using? What modloader are you using?
What exactly isn't working? Are you sure you are using a player charger and not a block charger?

**Comment by xDomso** [comment]
Minecraft version: 1.20.1
Wireless Chargers version: 1.0.9
Forge modloader version: 47.2.0
Iron Jetpacks version: 7.0.2
I'm really sorry it was late night and i crafted block charger as you write. Today i crafted player charger and it works! Im really apologize! But thanks you very much for your fast response! Keep good work!
