### ISSUE TITLE
[Bug] Wireless charger doesn't charge items in the Trinkets slots

### ISSUE THREAD

**Issue by shurik204** [SuperMartijn642/WirelessChargers#25]
**Version Info**
- Fabric 1.20.1
- Wireless Chargers 1.0.9

**Description of the Bug**
Charger voids energy trying to charge items in any Trinkets slot.

**Steps to Reproduce**
Put any chargeable item in the Trinkets slot.

**Screenshots**

https://github.com/SuperMartijn642/WirelessChargers/assets/43310372/779f5055-30f8-4d42-b454-2d8ab06e7680

The issue is [here](https://github.com/SuperMartijn642/WirelessChargers/blob/659931a44b6f1e7fa42b2257ca79319ac564f78e/src/main/java/com/supermartijn642/wirelesschargers/ChargerBlockEntity.java#L141C98-L141C138).
You're using `ContainerItemContext.withConstant` which doesn't store the item back. You need to create a class that extends `SnapshotParticipant<ItemVariant>` and implements `SingleSlotStorage<ItemVariant>` like [this](https://gist.github.com/shurik204/4aea0e30596688a0748d32ac34ffe2ce).

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.9a.
Thank you for reporting the issue!
