### ISSUE TITLE
[Bug] Wireless chargers charge blocks and player items, even when OFF

### ISSUE THREAD

**Issue by Jadan1213** [SuperMartijn642/WirelessChargers#26]
FORGE: 47.2.17
MC: 1.20.1
WC: 1.0.9-forge-mc1.20

https://github.com/SuperMartijn642/WirelessChargers/assets/68805162/c2bea3fd-b1b0-423a-b60b-19f3bb711bc4

**Comment by Jadan1213** [comment]
![image](https://github.com/SuperMartijn642/WirelessChargers/assets/68805162/318bd9e0-89b7-4dfb-8acc-36ad1724e087)

**Comment by SuperMartijn642** [comment]
Seems I broke it at some point, the redstone option was literally only checked when determining whether to do the spinning animation.
I fixed it now in version 1.0.9a.
Thank you for reporting the issue!
