### ISSUE TITLE
[Crash] Crash when rendering blocks from the mod.

### ISSUE THREAD

**Issue by EnderTheKnight** [SuperMartijn642/WirelessChargers#28]
**Version Info**

I'm using the Modrinth app.
- Minecraft 1.21.1
- Fabric loader version 0.16.8 
- Fabric API 0.107.0+1.21.1
- SuperMartijn642's Config Lib 1.1.8-fabric-mc1.21
- SuperMartijn642's Core Lib 1.1.17c-fabric-mc1.21
- Wireless Chargers 1.0.9-fabric-mc1.21

**Steps to Reproduce**
 Boot up the game with the specified mods and having a charger placed or seen in your inventory will crash the game.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/user-attachments/files/17592992/latest.log)

**Comment by SuperMartijn642** [comment]
This was already fixed in version 1.0.9a of Wireless Chargers for Fabric 1.21.1. Updating to that version should fix the issue.
